# Generated by Django 6.0 on 2026-01-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='show',
            table='shows',
        ),
    ]
