# Generated by Django 6.0 on 2025-12-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='screen',
        ),
    ]
