# Generated by Django 6.0 on 2026-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0003_show_created_at_show_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(),
        ),
    ]
