# Generated by Django 6.0 on 2026-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0004_alter_show_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
