# Generated by Django 6.0 on 2026-01-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0005_alter_show_show_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_date',
        ),
    ]
