# Generated by Django 6.0 on 2026-01-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0006_remove_show_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='name',
            field=models.CharField(default='name'),
        ),
    ]
