# Generated by Django 6.0 on 2025-12-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('release_date', models.DateField(null=True)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
            ],
        ),
    ]
