# Generated by Django 6.0 on 2025-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
