# Generated by Django 6.0 on 2025-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True),
        ),
    ]
