# Generated by Django 6.0 on 2025-12-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='theater_id',
            new_name='theater',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='user',
        ),
    ]
