# Generated by Django 6.0 on 2026-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
