# Generated by Django 6.0 on 2025-12-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_status'),
        ('theaters', '0003_screen_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='seats',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theaters.seat'),
        ),
    ]
