# Generated by Django 6.0 on 2025-12-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='seats',
        ),
    ]
