# Generated by Django 6.0 on 2025-12-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bookings_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='status',
        ),
    ]
