# Generated by Django 6.0 on 2025-12-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='screens',
        ),
    ]
