# Generated by Django 6.0 on 2026-01-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_screen_seat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='theater',
            table='theaters',
        ),
    ]
